// <auto-generated />
using System;
using BackendApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendApp.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20231209113902_UpdateOrder")]
    partial class UpdateOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendApp.Models.Basket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateAdded")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PublicUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublicUserId");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("BackendApp.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7808), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7811), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7813), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7814), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "LG"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7816), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7818), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Canon"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7820), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7821), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Nikon"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7823), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7825), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Google"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7827), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7828), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7831), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7832), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Nvidia"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7900), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7902), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "AMD"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7906), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7907), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "GIGABYTE"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7910), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7911), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "BenQ"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7913), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7915), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Intel"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7917), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7919), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Fujifilm"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7920), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7922), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Philips"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7924), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7925), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Lenovo"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7927), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7928), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Logitech"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7930), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7932), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Kingston"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7934), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7935), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Energizer"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7938), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7940), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Razer"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7942), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7943), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "be quiet!"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7945), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7946), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Xiaomi"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7948), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7950), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Razer"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7952), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7953), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Optoma"
                        });
                });

            modelBuilder.Entity("BackendApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("NameOfCategory")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7545), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7607), new TimeSpan(0, 2, 0, 0, 0)),
                            NameOfCategory = "Laptops, Tablets & PCs"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7611), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7612), new TimeSpan(0, 2, 0, 0, 0)),
                            NameOfCategory = "Computer & Office"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7615), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7616), new TimeSpan(0, 2, 0, 0, 0)),
                            NameOfCategory = "Hardware & Components"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7618), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7620), new TimeSpan(0, 2, 0, 0, 0)),
                            NameOfCategory = "Smartphones, Radio & GPS"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7622), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7623), new TimeSpan(0, 2, 0, 0, 0)),
                            NameOfCategory = "Photo / Video"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7625), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7626), new TimeSpan(0, 2, 0, 0, 0)),
                            NameOfCategory = "TV / HiFi / Video"
                        });
                });

            modelBuilder.Entity("BackendApp.Models.Favourite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateAdded")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Favourites");
                });

            modelBuilder.Entity("BackendApp.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BackendApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SubcategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BackendApp.Models.ProductBasket", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "BasketId");

                    b.HasIndex("BasketId");

                    b.ToTable("ProductBasket");
                });

            modelBuilder.Entity("BackendApp.Models.PublicUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("PublicUsers");
                });

            modelBuilder.Entity("BackendApp.Models.Subcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Subcategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7739), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7743), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Laptops / Notebooks"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7747), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7749), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Apple MacBook"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7751), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7752), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Monitors"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7755), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7756), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "All-in-One Printers"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7758), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7760), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Processors (CPUs)"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7762), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7763), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "AMD Graphics cards"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7765), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7767), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Smartphones & Cell Phones"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7769), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7771), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Apple iPhones"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7773), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7774), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Digital Cameras"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7776), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7778), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Instant Cameras"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7780), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7781), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "LED TV / LCD TV"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7783), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 12, 9, 13, 39, 2, 92, DateTimeKind.Unspecified).AddTicks(7785), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "OLED TV"
                        });
                });

            modelBuilder.Entity("BackendApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("PublicUserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PublicUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BackendApp.Models.Basket", b =>
                {
                    b.HasOne("BackendApp.Models.PublicUser", "PublicUser")
                        .WithMany()
                        .HasForeignKey("PublicUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PublicUser");
                });

            modelBuilder.Entity("BackendApp.Models.Favourite", b =>
                {
                    b.HasOne("BackendApp.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendApp.Models.Order", b =>
                {
                    b.HasOne("BackendApp.Models.Basket", "Basket")
                        .WithMany()
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");
                });

            modelBuilder.Entity("BackendApp.Models.Product", b =>
                {
                    b.HasOne("BackendApp.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Subcategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("BackendApp.Models.ProductBasket", b =>
                {
                    b.HasOne("BackendApp.Models.Basket", "Basket")
                        .WithMany("ProductBasket")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Product", "Product")
                        .WithMany("ProductBasket")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BackendApp.Models.Subcategory", b =>
                {
                    b.HasOne("BackendApp.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BackendApp.Models.User", b =>
                {
                    b.HasOne("BackendApp.Models.PublicUser", "PublicUser")
                        .WithMany()
                        .HasForeignKey("PublicUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PublicUser");
                });

            modelBuilder.Entity("BackendApp.Models.Basket", b =>
                {
                    b.Navigation("ProductBasket");
                });

            modelBuilder.Entity("BackendApp.Models.Product", b =>
                {
                    b.Navigation("ProductBasket");
                });
#pragma warning restore 612, 618
        }
    }
}
