// <auto-generated />
using System;
using BackendApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendApp.Migrations
{
    [DbContext(typeof(ShopContext))]
    [Migration("20231120162424_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendApp.Models.Basket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateAdded")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PublicUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublicUserId");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("BackendApp.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8905), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8907), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8911), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8912), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "LG"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8914), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8916), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Canon"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8917), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8919), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Nikon"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8921), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8922), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Google"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8924), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8926), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8928), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8929), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Nvidia"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8932), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8933), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "AMD"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8935), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8936), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "GIGABYTE"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8938), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8940), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "BenQ"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8942), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8943), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Intel"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8945), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8946), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Fujifilm"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8948), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8950), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Philips"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8952), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8953), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Panasonic"
                        });
                });

            modelBuilder.Entity("BackendApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("NameOfCategory")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8643), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8700), new TimeSpan(0, 2, 0, 0, 0)),
                            NameOfCategory = "Laptops, Tablets & PCs"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8705), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8707), new TimeSpan(0, 2, 0, 0, 0)),
                            NameOfCategory = "Computer & Office"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8709), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8710), new TimeSpan(0, 2, 0, 0, 0)),
                            NameOfCategory = "Hardware & Components"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8712), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8714), new TimeSpan(0, 2, 0, 0, 0)),
                            NameOfCategory = "Smartphones, Radio & GPS"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8716), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8717), new TimeSpan(0, 2, 0, 0, 0)),
                            NameOfCategory = "Photo / Video"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8719), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8721), new TimeSpan(0, 2, 0, 0, 0)),
                            NameOfCategory = "TV / HiFi / Video"
                        });
                });

            modelBuilder.Entity("BackendApp.Models.Favourite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("DateAdded")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Favourites");
                });

            modelBuilder.Entity("BackendApp.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BasketId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BackendApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SubcategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BackendApp.Models.ProductBasket", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "BasketId");

                    b.HasIndex("BasketId");

                    b.ToTable("ProductBasket");
                });

            modelBuilder.Entity("BackendApp.Models.PublicUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("PublicUsers");
                });

            modelBuilder.Entity("BackendApp.Models.Subcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Subcategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8841), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8845), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Laptops / Notebooks"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8848), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8849), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Apple MacBook"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8852), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8853), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Monitors"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8855), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8857), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "All-in-One Printers"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8859), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8860), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Processors (CPUs)"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8862), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8864), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "AMD Graphics cards"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8866), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8867), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Smartphones & Cell Phones"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8870), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8871), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Apple iPhones"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8873), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8875), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Digital Cameras"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8877), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8878), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "Instant Cameras"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8880), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8882), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "LED TV / LCD TV"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8884), new TimeSpan(0, 2, 0, 0, 0)),
                            CreatedBy = 0,
                            ModifiedAt = new DateTimeOffset(new DateTime(2023, 11, 20, 18, 24, 24, 544, DateTimeKind.Unspecified).AddTicks(8885), new TimeSpan(0, 2, 0, 0, 0)),
                            Name = "OLED TV"
                        });
                });

            modelBuilder.Entity("BackendApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("PublicUserId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PublicUserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BackendApp.Models.Basket", b =>
                {
                    b.HasOne("BackendApp.Models.PublicUser", "PublicUser")
                        .WithMany()
                        .HasForeignKey("PublicUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PublicUser");
                });

            modelBuilder.Entity("BackendApp.Models.Favourite", b =>
                {
                    b.HasOne("BackendApp.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackendApp.Models.Order", b =>
                {
                    b.HasOne("BackendApp.Models.Basket", "Basket")
                        .WithMany()
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");
                });

            modelBuilder.Entity("BackendApp.Models.Product", b =>
                {
                    b.HasOne("BackendApp.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Subcategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("BackendApp.Models.ProductBasket", b =>
                {
                    b.HasOne("BackendApp.Models.Basket", "Basket")
                        .WithMany("ProductBasket")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Product", "Product")
                        .WithMany("ProductBasket")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BackendApp.Models.Subcategory", b =>
                {
                    b.HasOne("BackendApp.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BackendApp.Models.User", b =>
                {
                    b.HasOne("BackendApp.Models.PublicUser", "PublicUser")
                        .WithMany()
                        .HasForeignKey("PublicUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PublicUser");
                });

            modelBuilder.Entity("BackendApp.Models.Basket", b =>
                {
                    b.Navigation("ProductBasket");
                });

            modelBuilder.Entity("BackendApp.Models.Product", b =>
                {
                    b.Navigation("ProductBasket");
                });
#pragma warning restore 612, 618
        }
    }
}
